name: "apps"
version: "3.8"
services:

  caddy:
    image: "docker.io/caddy:2.7"
    container_name: "apps-caddy"
    restart: "always"
    networks:
      - "public"
      - "private"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - "${CONFDIR:?}/caddy/Caddyfile:/etc/caddy/Caddyfile:Z"  # config
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificates
      - "${DATADIR:?}/caddy/data/:/data/:Z"
      - "${DATADIR:?}/caddy/config/:/config/:Z"
      - "${WEBDIR:?}/:/web/:ro"  # webserver
    environment:
      DOMAIN: "${DOMAIN:?}"

  dex:
    image: "ghcr.io/ict-vvf-genova/dex-smtp:master"
    container_name: "apps-dex"
    restart: "always"
    networks:
      - "public"
      - "private"
    volumes:
      - "./config/dex/config.yaml:/etc/dex/config.yaml:ro"
    environment:
      DEX_LOGLEVEL: "${DEX_LOGLEVEL:?}"
      DOMAIN: "${DOMAIN:?}"
      DEX_ADMIN_ONLY: "${DEX_ADMIN_ONLY:?}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:?}"
      DEFAULT_PASSWORD_HASH: "${DEFAULT_PASSWORD_HASH:?}"
      GRIST_OAUTH_CLIENT_SECRET: "${GRIST_OAUTH_CLIENT_SECRET:?}"
      DEX_LOGO_URL: "${DEX_LOGO_URL:?}"
      DEX_SMTP_NAME: "${DEX_SMTP_NAME:?}"
      DEX_SMTP_ID: "${DEX_SMTP_ID:?}"
      DEX_SMTP_HOST: "${DEX_SMTP_HOST:?}"
      DEX_SMTP_DOMAIN: "${DEX_SMTP_DOMAIN:?}"
      DEX_SMTP_LABEL: "${DEX_SMTP_LABEL:?}"
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5556/healthz"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2

  redis:
    image: "docker.io/redis:7-bookworm"
    container_name: "apps-redis"
    restart: "always"
    networks:
      - "private"
    volumes:
      - "${CONFDIR:?}/redis/redis.conf.sh:/etc/redis/redis.conf.sh:ro"
      - "${DATADIR:?}/redis/:/data/:Z"
    environment:
      REDIS_LOGLEVEL: "${REDIS_LOGLEVEL:?}"
      REDIS_AUTH: "${DEFAULT_PASSWORD:?}"
    command: ["sh", "-euc", "sh /etc/redis/redis.conf.sh | exec redis-server -"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping | grep -q PONG"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2

  grist:
    image: "docker.io/gristlabs/grist:1.1.11"
    container_name: "apps-grist"
    restart: "always"
    volumes:
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificates
      - "${DATADIR:?}/grist/:/persist/:Z"
    environment:
      DEBUG: ${GRIST_DEBUG:?}
      APP_HOME_URL: "https://grist.${DOMAIN:?}"
      GRIST_SESSION_SECRET: "${GRIST_SESSION_SECRET:?}"
      GRIST_SINGLE_ORG: "${GRIST_SINGLE_ORG:?}"
      GRIST_DEFAULT_EMAIL: "${ADMIN_EMAIL:?}"
      GRIST_SUPPORT_EMAIL: "${SUPPORT_EMAIL:?}"
      #GRIST_WIDGET_LIST_URL: "${GRIST_WIDGET_LIST_URL:?}"
      # Predefined  # FIXME custom widgets not listed, but callable, no proxy?
      GRIST_SANDBOX_FLAVOR: "gvisor"
      GRIST_PAGE_TITLE_SUFFIX: "_blank"
      GRIST_TELEMETRY_LEVEL: "off"
      GRIST_MAX_UPLOAD_ATTACHMENT_MB: "10"
      GRIST_MAX_UPLOAD_IMPORT_MB: "50"
      GRIST_THROTTLE_CPU: "true"
      # OIDC Authentication
      GRIST_OIDC_IDP_ISSUER: "https://dex.${DOMAIN:?}/.well-known/openid-configuration"
      GRIST_OIDC_IDP_CLIENT_ID: "grist"
      GRIST_OIDC_IDP_CLIENT_SECRET: "${GRIST_OAUTH_CLIENT_SECRET:?}"
      GRIST_OIDC_IDP_SCOPES: "openid email profile"
      GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: "true"
      NODE_EXTRA_CA_CERTS: "/etc/certs/rootCA.pem"  # trust dex
      #GRIST_FORCE_LOGIN: "true"  # no unauthenticated users
      #GRIST_SUPPORT_ANON: "false"  # no anonymous users
      # Redis
      REDIS_URL: "redis://:${DEFAULT_PASSWORD:?}@redis:6379/1"
      # Proxy
      GRIST_HTTPS_PROXY: "${HTTP_PROXY}"
      http_proxy:  "${HTTP_PROXY}"
      HTTP_PROXY: "${HTTP_PROXY}"
      https_proxy:  "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTP_PROXY}"
      no_proxy:  "${NO_PROXY}"
      NO_PROXY: "${NO_PROXY}"
    networks:
      - "public"
      - "private"
    healthcheck:
      test: ["CMD", "bash", "-euc", ">/dev/tcp/localhost/8484"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2
    depends_on:
      dex:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"

  nodered:
    image: "docker.io/nodered/node-red:latest"
    container_name: "apps-nodered"
    restart: "always"
    volumes:
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificates
      - "./config/nodered/settings.js:/data/settings.js:ro"  # settings
      - "./data/nodered/:/data/:Z"
    user: "0:0"
    environment:
      NODERED_LOGLEVEL: "${NODERED_LOGLEVEL:?}"
      NODERED_SESSION_SECRET: "${NODERED_SESSION_SECRET:?}"
      NODERED_ADMIN: "${NODERED_ADMIN:?}"
      NODERED_PASSWORD_HASH: "${NODERED_PASSWORD_HASH:?}"
      TZ: "Europe/Rome"
      NODE_EXTRA_CA_CERTS: "/etc/certs/rootCA.pem"  # trust grist
      # Proxy
      http_proxy:  "${HTTP_PROXY}"
      HTTP_PROXY: "${HTTP_PROXY}"
      https_proxy:  "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTP_PROXY}"
      no_proxy:  "${NO_PROXY}"
      NO_PROXY: "${NO_PROXY}"
    networks:
      - "public"
      - "private"

networks:

  public:
    name: "apps-public"
    internal: false

  private:
    name: "apps-private"
    internal: true
