name: "apps"
version: "3.8"
services:

  caddy:
    image: "docker.io/caddy:2.7"
    container_name: "apps-caddy"
    restart: "always"
    user: "${UID:?}:${GID:?}"
    networks:
      - "public"
      - "private"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - "${CONFDIR:?}/caddy/Caddyfile:/etc/caddy/Caddyfile:Z"  # config
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificates
      - "${DATADIR:?}/caddy/data/:/data/:Z"
      - "${DATADIR:?}/caddy/config/:/config/:Z"
      - "${WEBDIR:?}/:/web/:ro"  # webserver
    environment:
      DOMAIN: "${DOMAIN:?}"
      CADDY_LOGLEVEL: "${CADDY_LOGLEVEL:?}"

  dex:
    image: "ghcr.io/ict-vvf-genova/dex-smtp:master"
    container_name: "apps-dex"
    restart: "always"
    networks:
      - "public"
      - "private"
    volumes:
      - "./config/dex/config.yaml:/etc/dex/config.yaml:ro"
    environment:
      DEX_LOGLEVEL: "${DEX_LOGLEVEL:?}"
      DOMAIN: "${DOMAIN:?}"
      DEX_ADMIN_ONLY: "${DEX_ADMIN_ONLY:?}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:?}"
      DEFAULT_PASSWORD_HASH: "${DEFAULT_PASSWORD_HASH:?}"
      GRIST_OAUTH_CLIENT_SECRET: "${GRIST_OAUTH_CLIENT_SECRET:?}"
      DEX_SMTP_NAME: "${DEX_SMTP_NAME:?}"
      DEX_SMTP_ID: "${DEX_SMTP_ID:?}"
      DEX_SMTP_HOST: "${DEX_SMTP_HOST:?}"
      DEX_SMTP_DOMAIN: "${DEX_SMTP_DOMAIN:?}"
      DEX_SMTP_LABEL: "${DEX_SMTP_LABEL:?}"
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5556/healthz"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2

  redis:
    image: "docker.io/redis:7-bookworm"
    container_name: "apps-redis"
    restart: "always"
    user: "${UID:?}:${GID:?}"
    networks:
      - "private"
    volumes:
      - "${CONFDIR:?}/redis/redis.conf.sh:/etc/redis/redis.conf.sh:ro"
      - "${DATADIR:?}/redis/:/data/:Z"
    environment:
      REDIS_LOGLEVEL: "${REDIS_LOGLEVEL:?}"
      REDIS_AUTH: "${DEFAULT_PASSWORD:?}"
    command: ["sh", "-euc", "sh /etc/redis/redis.conf.sh | exec redis-server -"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping | grep -q PONG"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2

  grist:
    image: "docker.io/gristlabs/grist:1.2.1"
    container_name: "apps-grist"
    restart: "always"
    user: "${UID:?}:${GID:?}"
    volumes:
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificate dir
      - "${DATADIR:?}/grist/persist/:/persist/:Z"  # persist dir
      - "${DATADIR:?}/grist/user/:/user/:Z"  # user dir, eg. my-widgets
    environment:
      DEBUG: ${GRIST_DEBUG}
      APP_HOME_URL: "https://grist.${DOMAIN:?}"
      # APP_DOC_INTERNAL_URL: "http://localhost:8484" # as previous from within
      GRIST_SESSION_SECRET: "${GRIST_SESSION_SECRET:?}"
      GRIST_BOOT_KEY: "${GRIST_BOOT_KEY:?}"
      GRIST_SINGLE_ORG: "${GRIST_SINGLE_ORG:?}"
      # Widgets
      GRIST_WIDGET_LIST_URL: ""
      # GRIST_WIDGET_LIST_URL: "https://gristlabs.github.io/grist-widget/manifest.json"
      GRIST_EXPERIMENTAL_PLUGINS: 1
      GRIST_USER_ROOT: "/user/"  # local plugins path
      GRIST_TRUST_PLUGINS: 1  # serve local plugins along with the Grist app
      # Predefined
      GRIST_SANDBOX_FLAVOR: "gvisor"
      GRIST_PAGE_TITLE_SUFFIX: "_blank"
      GRIST_TELEMETRY_LEVEL: "off"  # not working behind proxy
      GRIST_MAX_UPLOAD_ATTACHMENT_MB: "10"
      GRIST_MAX_UPLOAD_IMPORT_MB: "50"
      GRIST_THROTTLE_CPU: "true"
      # OIDC Authentication
      GRIST_OIDC_IDP_ISSUER: "https://dex.${DOMAIN:?}/.well-known/openid-configuration"
      GRIST_OIDC_IDP_CLIENT_ID: "grist"
      GRIST_OIDC_IDP_CLIENT_SECRET: "${GRIST_OAUTH_CLIENT_SECRET:?}"
      GRIST_OIDC_IDP_SCOPES: "openid email profile"
      GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT: "true"
      NODE_EXTRA_CA_CERTS: "/etc/certs/rootCA.pem"  # trust dex
      GRIST_FORCE_LOGIN: "true"  # no unauthenticated users
      GRIST_SUPPORT_ANON: "false"  # no anonymous users
      # Redis
      REDIS_URL: "redis://:${DEFAULT_PASSWORD:?}@redis:6379/1"
      # Proxy
      # GRIST_HTTPS_PROXY: "${HTTP_PROXY}"
      # http_proxy:  "${HTTP_PROXY}"
      # HTTP_PROXY: "${HTTP_PROXY}"
      # https_proxy:  "${HTTP_PROXY}"
      # HTTPS_PROXY: "${HTTP_PROXY}"
      # no_proxy:  "${NO_PROXY}"
      # NO_PROXY: "${NO_PROXY}"
      # Customization
      GRIST_DEFAULT_EMAIL: "${ADMIN_EMAIL:?}"
      GRIST_SUPPORT_EMAIL: "${SUPPORT_EMAIL:?}"
      # GRIST_TERMS_OF_SERVICE_URL: ""
    networks:
      - "public"
      - "private"
    healthcheck:
      test: ["CMD", "bash", "-euc", ">/dev/tcp/localhost/8484"]
      start_period: "5m"
      interval: "10s"
      timeout: "5s"
      retries: 2
    depends_on:
      dex:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"

  nodered:
    image: "docker.io/nodered/node-red:3.1.8"
    container_name: "apps-nodered"
    restart: "always"
    user: "${UID:?}:${GID:?}"
    volumes:
      - "${CERTDIR:?}/:/etc/certs/:Z"  # certificates
      - "./config/nodered/settings.js:/data/settings.js:ro"  # settings
      - "./data/nodered/:/data/:Z"
    environment:
      NODERED_LOGLEVEL: "${NODERED_LOGLEVEL:?}"
      NODERED_SESSION_SECRET: "${NODERED_SESSION_SECRET:?}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:?}"
      DEFAULT_PASSWORD_HASH: "${DEFAULT_PASSWORD_HASH:?}"
      TZ: "Europe/Rome"
      NODE_EXTRA_CA_CERTS: "/etc/certs/rootCA.pem"  # trust grist
      # Grist doc references
      VF_CODICI_SEDE: "${VF_CODICI_SEDE:?}"
      GRIST_DOC_ID: "${GRIST_DOC_ID:?}"
      GRIST_API_KEY: "${GRIST_API_KEY:?}"
      # Proxy
      http_proxy:  "${HTTP_PROXY}"
      HTTP_PROXY: "${HTTP_PROXY}"
      https_proxy:  "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTP_PROXY}"
      no_proxy:  "${NO_PROXY}"
      NO_PROXY: "${NO_PROXY}"
    networks:
      - "public"
      - "private"
    depends_on:
      grist:
        condition: "service_healthy"

networks:

  public:
    name: "apps-public"
    internal: false

  private:
    name: "apps-private"
    internal: true
