issuer: "https://dex.{{ .Env.DOMAIN }}"

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: "0.0.0.0:5556"

logger:
  level: "{{ .Env.DEX_LOGLEVEL }}"
  format: "text"

frontend:
  issuer: "Welcome"
  logoURL: '{{ getenv "DEX_LOGO_URL" }}'
  theme: "light"

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false

staticClients:
  - name: "Grist"
    id: "grist"
    secret: "{{ .Env.GRIST_OAUTH_CLIENT_SECRET }}"
    redirectURIs: ["https://grist.{{ .Env.DOMAIN }}/oauth2/callback"]

{{ $test := .Env.DEX_ADMIN_ONLY }}
{{ if eq $test "true" }}
enablePasswordDB: true
staticPasswords:
  - username: "admin"
    email: "{{ .Env.ADMIN_EMAIL }}"
    hash: "{{ .Env.DEFAULT_PASSWORD_HASH }}"
{{ else }}
connectors:
- type: smtp
  name: "{{ .Env.DEX_SMTP_NAME }}"
  id: "{{ .Env.DEX_SMTP_ID }}"
  config:
    host: "{{ .Env.DEX_SMTP_HOST }}"
    domain: "{{ .Env.DEX_SMTP_DOMAIN }}"
    label: "{{ .Env.DEX_SMTP_LABEL }}"
{{ end }}

